export const courses = [
  {
    id: 'system-design',
    slug: 'system-design',
    title: 'System Design',
    description: 'Master distributed systems, scalability, and architecture patterns used at top companies.',
    icon: '🏗️',
    difficulty: 'Intermediate',
    totalTopics: 24,
    estimatedHours: 40,
    category: 'system-design',
    sections: [
      {
        id: 'fundamentals',
        title: 'Fundamentals',
        topics: [
          { id: 'intro', title: 'Introduction to System Design', isPremium: false, estimatedReadTime: 8 },
          { id: 'scalability', title: 'Scalability Basics', isPremium: false, estimatedReadTime: 12 },
          { id: 'load-balancing', title: 'Load Balancing', isPremium: false, estimatedReadTime: 15 },
          { id: 'caching', title: 'Caching Strategies', isPremium: true, estimatedReadTime: 18 },
          { id: 'databases', title: 'Database Design at Scale', isPremium: true, estimatedReadTime: 20 },
        ],
      },
      {
        id: 'advanced',
        title: 'Advanced Patterns',
        topics: [
          { id: 'microservices', title: 'Microservices Architecture', isPremium: true, estimatedReadTime: 25 },
          { id: 'event-driven', title: 'Event-Driven Architecture', isPremium: true, estimatedReadTime: 20 },
          { id: 'cap-theorem', title: 'CAP Theorem & Consistency', isPremium: true, estimatedReadTime: 15 },
        ],
      },
      {
        id: 'case-studies',
        title: 'Case Studies',
        topics: [
          { id: 'design-twitter', title: 'Design Twitter', isPremium: true, estimatedReadTime: 30 },
          { id: 'design-youtube', title: 'Design YouTube', isPremium: true, estimatedReadTime: 30 },
          { id: 'design-uber', title: 'Design Uber', isPremium: true, estimatedReadTime: 30 },
        ],
      },
    ],
  },
  {
    id: 'kafka',
    slug: 'kafka',
    title: 'Apache Kafka',
    description: 'Learn event streaming, real-time data pipelines, and Kafka internals from the ground up.',
    icon: '⚡',
    difficulty: 'Intermediate',
    totalTopics: 18,
    estimatedHours: 30,
    category: 'kafka',
    sections: [
      {
        id: 'basics',
        title: 'Kafka Basics',
        topics: [
          { id: 'intro', title: 'What is Apache Kafka?', isPremium: false, estimatedReadTime: 10 },
          { id: 'architecture', title: 'Kafka Architecture', isPremium: false, estimatedReadTime: 15 },
          { id: 'topics-partitions', title: 'Topics & Partitions', isPremium: false, estimatedReadTime: 12 },
          { id: 'producers', title: 'Producers & Consumers', isPremium: true, estimatedReadTime: 18 },
        ],
      },
      {
        id: 'advanced-kafka',
        title: 'Advanced Kafka',
        topics: [
          { id: 'streams', title: 'Kafka Streams', isPremium: true, estimatedReadTime: 22 },
          { id: 'connect', title: 'Kafka Connect', isPremium: true, estimatedReadTime: 20 },
          { id: 'schema-registry', title: 'Schema Registry', isPremium: true, estimatedReadTime: 15 },
        ],
      },
    ],
  },
  {
    id: 'lld',
    slug: 'lld',
    title: 'Low Level Design',
    description: 'Master object-oriented design, design patterns, and SOLID principles.',
    icon: '🔧',
    difficulty: 'Intermediate',
    totalTopics: 20,
    estimatedHours: 35,
    category: 'lld',
    sections: [
      {
        id: 'oop',
        title: 'OOP & Design Principles',
        topics: [
          { id: 'solid', title: 'SOLID Principles', isPremium: false, estimatedReadTime: 15 },
          { id: 'design-patterns', title: 'Design Patterns Overview', isPremium: false, estimatedReadTime: 20 },
          { id: 'creational', title: 'Creational Patterns', isPremium: true, estimatedReadTime: 25 },
        ],
      },
    ],
  },
  {
    id: 'aws',
    slug: 'aws',
    title: 'AWS for Engineers',
    description: 'Core AWS services, architecture best practices, and hands-on patterns.',
    icon: '☁️',
    difficulty: 'Beginner',
    totalTopics: 22,
    estimatedHours: 45,
    category: 'aws',
    sections: [
      {
        id: 'fundamentals',
        title: 'AWS Fundamentals',
        topics: [
          { id: 'intro', title: 'Introduction to AWS', isPremium: false, estimatedReadTime: 10 },
          { id: 'ec2', title: 'EC2 & Compute', isPremium: false, estimatedReadTime: 18 },
          { id: 's3', title: 'S3 & Storage', isPremium: true, estimatedReadTime: 15 },
        ],
      },
    ],
  },
]

export const topicContent = {
  intro: {
    heading: 'Introduction to System Design',
    estimatedReadTime: 8,
    isPremium: false,
    blocks: [
      { type: 'text', content: 'System design is the process of defining the architecture, components, modules, interfaces, and data flow of a system to satisfy specified requirements. It is a crucial skill for senior software engineers and is heavily tested in technical interviews at top companies like Google, Meta, Amazon, and Microsoft.' },
      { type: 'smallHeading', content: 'Why System Design Matters' },
      { type: 'text', content: 'As a software engineer, you will frequently need to design large-scale systems that serve millions of users. Understanding system design helps you:' },
      { type: 'list', content: ['Build scalable and reliable systems', 'Make informed architectural decisions', 'Communicate design choices to your team', 'Ace technical interviews at top companies'] },
      { type: 'smallHeading', content: 'Key Concepts to Master' },
      { type: 'text', content: 'A solid understanding of system design requires familiarity with several foundational concepts:' },
      { type: 'table', content: { headers: ['Concept', 'Importance', 'Complexity'], rows: [['Scalability', 'Critical', 'Medium'], ['Load Balancing', 'High', 'Low'], ['Caching', 'High', 'Medium'], ['Database Sharding', 'High', 'High'], ['CAP Theorem', 'Critical', 'High']] } },
      { type: 'smallHeading', content: 'The System Design Interview' },
      { type: 'text', content: 'In a typical system design interview, you will be given a vague problem statement like "Design Twitter" or "Design a URL shortener". The interviewer wants to see how you:' },
      { type: 'orderedList', content: ['Clarify requirements and constraints', 'Estimate scale (users, data, traffic)', 'Define the high-level architecture', 'Deep dive into specific components', 'Discuss trade-offs and bottlenecks'] },
      { type: 'callout', content: { type: 'tip', text: 'Always start by asking clarifying questions. Never assume the requirements — make sure you understand the scale, features, and constraints before diving into the design.' } },
      { type: 'smallHeading', content: 'Sample Code: Basic Rate Limiter' },
      { type: 'code', content: { language: 'python', code: `class RateLimiter:\n    def __init__(self, max_requests: int, window_seconds: int):\n        self.max_requests = max_requests\n        self.window_seconds = window_seconds\n        self.requests = {}  # user_id -> list of timestamps\n    \n    def is_allowed(self, user_id: str) -> bool:\n        import time\n        now = time.time()\n        window_start = now - self.window_seconds\n        \n        if user_id not in self.requests:\n            self.requests[user_id] = []\n        \n        # Remove old requests outside the window\n        self.requests[user_id] = [\n            ts for ts in self.requests[user_id] \n            if ts > window_start\n        ]\n        \n        if len(self.requests[user_id]) < self.max_requests:\n            self.requests[user_id].append(now)\n            return True\n        return False` } },
    ],
  },
}

export const blogs = [
  {
    id: '1',
    slug: 'caching-strategy',
    title: 'Caching Is Not Just About Speed — It\'s About Strategy',
    subtitle: 'Why smart caching decisions can make or break your system design.',
    tags: ['System Design', 'Caching', 'Performance'],
    coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=400&fit=crop',
    rating: 4.9,
    readTime: 8,
    publishedAt: 'May 18, 2026',
    author: 'Rahul Sharma',
  },
  {
    id: '2',
    slug: 'why-netflix-never-crashes',
    title: 'Why Netflix Never Crashes: Resilience Patterns Explained',
    subtitle: 'A deep dive into circuit breakers, fallbacks, and chaos engineering.',
    tags: ['System Design', 'Resilience', 'Netflix'],
    coverImage: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&h=400&fit=crop',
    rating: 4.9,
    readTime: 12,
    publishedAt: 'May 15, 2026',
    author: 'Priya Verma',
  },
  {
    id: '3',
    slug: 'sql-vs-nosql',
    title: 'SQL vs NoSQL vs Search Engines: When to Use What',
    subtitle: 'Understanding the trade-offs between different storage solutions.',
    tags: ['Databases', 'SQL', 'NoSQL'],
    coverImage: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&h=400&fit=crop',
    rating: 4.8,
    readTime: 10,
    publishedAt: 'May 10, 2026',
    author: 'Amit Patel',
  },
  {
    id: '4',
    slug: 'kafka-vs-rabbitmq',
    title: 'Kafka vs RabbitMQ: Choosing the Right Message Broker',
    subtitle: 'A practical comparison to help you make the right architectural decision.',
    tags: ['Kafka', 'Message Queues', 'Architecture'],
    coverImage: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&h=400&fit=crop',
    rating: 4.7,
    readTime: 9,
    publishedAt: 'May 5, 2026',
    author: 'Deepak Singh',
  },
  {
    id: '5',
    slug: 'microservices-pitfalls',
    title: '7 Microservices Mistakes That Will Hurt You in Production',
    subtitle: 'Learn from real-world failures to build better distributed systems.',
    tags: ['Microservices', 'Best Practices', 'Production'],
    coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop',
    rating: 4.8,
    readTime: 11,
    publishedAt: 'April 28, 2026',
    author: 'Rahul Sharma',
  },
  {
    id: '6',
    slug: 'consistent-hashing',
    title: 'Consistent Hashing: The Algorithm Behind Distributed Caches',
    subtitle: 'How Cassandra, DynamoDB, and Redis Cluster handle node failures gracefully.',
    tags: ['Algorithms', 'Distributed Systems', 'Hashing'],
    coverImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&h=400&fit=crop',
    rating: 4.9,
    readTime: 14,
    publishedAt: 'April 20, 2026',
    author: 'Priya Verma',
  },
]

export const adminStats = {
  totalUsers: 12847,
  premiumUsers: 3241,
  totalTopics: 87,
  totalBlogs: 24,
  dailyActiveUsers: 1423,
  mrr: 94999,
  newSignupsThisMonth: 842,
  newSubscribersThisMonth: 156,
}

export const adminUsers = [
  { id: '1', name: 'Rahul Sharma', email: 'rahul@example.com', role: 'admin', status: 'pro', joinedAt: 'Jan 15, 2026', lastLogin: '2 hours ago' },
  { id: '2', name: 'Priya Verma', email: 'priya@example.com', role: 'author', status: 'pro', joinedAt: 'Feb 3, 2026', lastLogin: '1 day ago' },
  { id: '3', name: 'Amit Patel', email: 'amit@example.com', role: 'free_user', status: 'free', joinedAt: 'Mar 12, 2026', lastLogin: '3 days ago' },
  { id: '4', name: 'Sneha Gupta', email: 'sneha@example.com', role: 'premium_user', status: 'pro', joinedAt: 'Mar 20, 2026', lastLogin: '5 hours ago' },
  { id: '5', name: 'Rohan Mehta', email: 'rohan@example.com', role: 'free_user', status: 'free', joinedAt: 'Apr 1, 2026', lastLogin: 'Just now' },
  { id: '6', name: 'Kavita Joshi', email: 'kavita@example.com', role: 'premium_user', status: 'pro', joinedAt: 'Apr 8, 2026', lastLogin: '12 hours ago' },
  { id: '7', name: 'Vikram Nair', email: 'vikram@example.com', role: 'free_user', status: 'free', joinedAt: 'Apr 15, 2026', lastLogin: '1 week ago' },
  { id: '8', name: 'Ananya Das', email: 'ananya@example.com', role: 'premium_user', status: 'pro', joinedAt: 'May 2, 2026', lastLogin: '2 days ago' },
]

export const adminContent = [
  { id: '1', title: 'Introduction to System Design', type: 'topic', course: 'System Design', status: 'published', isPremium: false, updatedAt: 'May 20, 2026' },
  { id: '2', title: 'Load Balancing Deep Dive', type: 'topic', course: 'System Design', status: 'published', isPremium: false, updatedAt: 'May 18, 2026' },
  { id: '3', title: 'Caching Strategies', type: 'topic', course: 'System Design', status: 'published', isPremium: true, updatedAt: 'May 15, 2026' },
  { id: '4', title: 'Database Design at Scale', type: 'topic', course: 'System Design', status: 'published', isPremium: true, updatedAt: 'May 10, 2026' },
  { id: '5', title: 'What is Apache Kafka?', type: 'topic', course: 'Apache Kafka', status: 'published', isPremium: false, updatedAt: 'May 8, 2026' },
  { id: '6', title: 'Kafka Streams', type: 'topic', course: 'Apache Kafka', status: 'published', isPremium: true, updatedAt: 'May 5, 2026' },
  { id: '7', title: 'SOLID Principles', type: 'topic', course: 'LLD', status: 'published', isPremium: false, updatedAt: 'Apr 28, 2026' },
  { id: '8', title: 'Microservices Architecture', type: 'topic', course: 'System Design', status: 'draft', isPremium: true, updatedAt: 'May 21, 2026' },
  { id: '9', title: 'Caching Is Not Just About Speed', type: 'blog', course: '—', status: 'published', isPremium: false, updatedAt: 'May 18, 2026' },
  { id: '10', title: 'Why Netflix Never Crashes', type: 'blog', course: '—', status: 'published', isPremium: false, updatedAt: 'May 15, 2026' },
  { id: '11', title: 'Design Twitter Case Study', type: 'topic', course: 'System Design', status: 'draft', isPremium: true, updatedAt: 'May 21, 2026' },
  { id: '12', title: 'Consistent Hashing Explained', type: 'blog', course: '—', status: 'published', isPremium: false, updatedAt: 'Apr 20, 2026' },
]
